repo_url: https://github.com/mbroedl/cognitive-tasks-for-expyriment/
theme: cinder
extra_css:
  - css/custom.css
  - css/pygments.css
markdown_extensions:
  - footnotes
  - codehilite
  - smarty
  - toc:
        permalink: "#"

site_name: Cognitive Tasks for Expyriment
site_author: github/mbroedl
site_description: A battery of Cognitive Tasks for Expyriment. Suitable for android and desktop environments.
docs_dir: 'docs'

nav:
- Home: index.md
- How To:
    - Installation: howto/install.md
    - Configuration: howto/configuration.md
    - Instructions and Languages: howto/translations.md
    - Creating Logs: howto/logs.md
    - Developing or Modifying: howto/developing.md
- Tasks:
    - Simple Reaction Time Task: tasks/rt_simple.md
    - N-Back: tasks/nback.md
    - Trail Making Task: tasks/trailmaking.md
    - Digit Span Task: tasks/digitspan.md
- About:
    - Using and Citing: about/using-and-citing.md
    - Release Notes: about/release-notes.md
- Download: https://github.com/mbroedl/cognitive-tasks-for-expyriment/releases

copyright: "All experiments here are licensed under the <a href='https://github.com/mbroedl/cognitive-tasks-for-expyriment/COPYING'>GPLv3 license</a>.<br />If you use any of these experiments for scientific publications, please <a href='/about/using-and-citing/'>cite the authors</a>."
